apiVersion: apps/v1
kind: Deployment
metadata:
  name: resilient-workload-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: resilient-workload-app
  template:
    metadata:
      labels:
        app: resilient-workload-app
    spec:
      containers:
      - name: resilient-workload-app
        image: resilient-workload-app:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
        startupProbe:
          httpGet:
            path: /start
            port: 3000
          failureThreshold: 2
          periodSeconds: 20
        livenessProbe:
          httpGet:
            path: /live
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /ready
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
